// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tickett.Data;

#nullable disable

namespace Tickett.Data.Migrations
{
    [DbContext(typeof(ObraContext))]
    [Migration("20240222152845_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Tickett.Models.Butaca", b =>
                {
                    b.Property<int>("ButacaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ButacaId"), 1L, 1);

                    b.Property<bool>("Libre")
                        .HasColumnType("bit");

                    b.Property<int>("ObraId")
                        .HasColumnType("int");

                    b.Property<int?>("SesionId")
                        .HasColumnType("int");

                    b.HasKey("ButacaId");

                    b.HasIndex("ObraId");

                    b.HasIndex("SesionId");

                    b.ToTable("Butacas");
                });

            modelBuilder.Entity("Tickett.Models.Obra", b =>
                {
                    b.Property<int>("ObraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ObraId"), 1L, 1);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DiaObra")
                        .HasColumnType("datetime2");

                    b.Property<int>("Duracion")
                        .HasColumnType("int");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("HoraObra")
                        .HasColumnType("time");

                    b.Property<string>("Imagen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Precio")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ObraId");

                    b.ToTable("Obras");

                    b.HasData(
                        new
                        {
                            ObraId = 1,
                            Descripcion = "false",
                            DiaObra = new DateTime(2024, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Duracion = 105,
                            Genero = "Drama",
                            HoraObra = new TimeSpan(0, 17, 0, 0, 0),
                            Imagen = "donjuan.jpg",
                            Precio = 25,
                            Titulo = "Don Juan"
                        },
                        new
                        {
                            ObraId = 2,
                            Descripcion = "false",
                            DiaObra = new DateTime(2024, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Duracion = 120,
                            Genero = "Drama",
                            HoraObra = new TimeSpan(0, 18, 30, 0, 0),
                            Imagen = "celestina.jpg",
                            Precio = 15,
                            Titulo = "Celestina"
                        },
                        new
                        {
                            ObraId = 3,
                            Descripcion = "false",
                            DiaObra = new DateTime(2024, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Duracion = 115,
                            Genero = "Drama",
                            HoraObra = new TimeSpan(0, 16, 0, 0, 0),
                            Imagen = "doble-o-nada.jpg",
                            Precio = 20,
                            Titulo = "Doble o nada"
                        },
                        new
                        {
                            ObraId = 4,
                            Descripcion = "false",
                            DiaObra = new DateTime(2024, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Duracion = 140,
                            Genero = "Drama",
                            HoraObra = new TimeSpan(0, 19, 15, 0, 0),
                            Imagen = "campeones.jpg",
                            Precio = 35,
                            Titulo = "Campeones"
                        },
                        new
                        {
                            ObraId = 5,
                            Descripcion = "false",
                            DiaObra = new DateTime(2024, 2, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Duracion = 135,
                            Genero = "Drama",
                            HoraObra = new TimeSpan(0, 18, 0, 0, 0),
                            Imagen = "el-mago-pop.jpg",
                            Precio = 30,
                            Titulo = "El mago Pop"
                        },
                        new
                        {
                            ObraId = 6,
                            Descripcion = "false",
                            DiaObra = new DateTime(2024, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Duracion = 100,
                            Genero = "Drama",
                            HoraObra = new TimeSpan(0, 12, 0, 0, 0),
                            Imagen = "ElReyLeon3Aniv200.jpg",
                            Precio = 10,
                            Titulo = "El Rey Leon"
                        },
                        new
                        {
                            ObraId = 7,
                            Descripcion = "false",
                            DiaObra = new DateTime(2024, 3, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Duracion = 90,
                            Genero = "Drama",
                            HoraObra = new TimeSpan(0, 20, 0, 0, 0),
                            Imagen = "fango.jpg",
                            Precio = 40,
                            Titulo = "Fango"
                        },
                        new
                        {
                            ObraId = 8,
                            Descripcion = "false",
                            DiaObra = new DateTime(2024, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Duracion = 110,
                            Genero = "Drama",
                            HoraObra = new TimeSpan(0, 20, 30, 0, 0),
                            Imagen = "funcion-sale.mal.jpg",
                            Precio = 30,
                            Titulo = "La Funcion que Sale Mal"
                        },
                        new
                        {
                            ObraId = 9,
                            Descripcion = "false",
                            DiaObra = new DateTime(2024, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Duracion = 120,
                            Genero = "Drama",
                            HoraObra = new TimeSpan(0, 15, 15, 0, 0),
                            Imagen = "ilusionate.jpg",
                            Precio = 15,
                            Titulo = "Ilusionate"
                        },
                        new
                        {
                            ObraId = 10,
                            Descripcion = "false",
                            DiaObra = new DateTime(2024, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Duracion = 105,
                            Genero = "Drama",
                            HoraObra = new TimeSpan(0, 22, 15, 0, 0),
                            Imagen = "jose-el-sonador.jpg",
                            Precio = 25,
                            Titulo = "Jose el soñador"
                        },
                        new
                        {
                            ObraId = 11,
                            Descripcion = "false",
                            DiaObra = new DateTime(2024, 4, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Duracion = 125,
                            Genero = "Drama",
                            HoraObra = new TimeSpan(0, 21, 30, 0, 0),
                            Imagen = "laponia.jpg",
                            Precio = 20,
                            Titulo = "Laponia"
                        },
                        new
                        {
                            ObraId = 12,
                            Descripcion = "false",
                            DiaObra = new DateTime(2024, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Duracion = 30,
                            Genero = "Drama",
                            HoraObra = new TimeSpan(0, 19, 15, 0, 0),
                            Imagen = "las-mil-y-una-noches.jpg",
                            Precio = 25,
                            Titulo = "Las mil y una noches"
                        });
                });

            modelBuilder.Entity("Tickett.Models.ObraReparto", b =>
                {
                    b.Property<int>("ObraId")
                        .HasColumnType("int");

                    b.Property<int>("RepartoId")
                        .HasColumnType("int");

                    b.HasKey("ObraId", "RepartoId");

                    b.HasIndex("RepartoId");

                    b.ToTable("ObraRepartos");

                    b.HasData(
                        new
                        {
                            ObraId = 1,
                            RepartoId = 1
                        },
                        new
                        {
                            ObraId = 1,
                            RepartoId = 2
                        },
                        new
                        {
                            ObraId = 1,
                            RepartoId = 3
                        },
                        new
                        {
                            ObraId = 1,
                            RepartoId = 4
                        },
                        new
                        {
                            ObraId = 1,
                            RepartoId = 5
                        },
                        new
                        {
                            ObraId = 1,
                            RepartoId = 6
                        },
                        new
                        {
                            ObraId = 1,
                            RepartoId = 7
                        },
                        new
                        {
                            ObraId = 1,
                            RepartoId = 8
                        },
                        new
                        {
                            ObraId = 2,
                            RepartoId = 9
                        },
                        new
                        {
                            ObraId = 2,
                            RepartoId = 10
                        },
                        new
                        {
                            ObraId = 2,
                            RepartoId = 11
                        },
                        new
                        {
                            ObraId = 2,
                            RepartoId = 12
                        },
                        new
                        {
                            ObraId = 2,
                            RepartoId = 13
                        },
                        new
                        {
                            ObraId = 2,
                            RepartoId = 14
                        },
                        new
                        {
                            ObraId = 2,
                            RepartoId = 15
                        },
                        new
                        {
                            ObraId = 2,
                            RepartoId = 16
                        },
                        new
                        {
                            ObraId = 3,
                            RepartoId = 17
                        },
                        new
                        {
                            ObraId = 3,
                            RepartoId = 18
                        },
                        new
                        {
                            ObraId = 3,
                            RepartoId = 19
                        },
                        new
                        {
                            ObraId = 3,
                            RepartoId = 20
                        },
                        new
                        {
                            ObraId = 3,
                            RepartoId = 21
                        },
                        new
                        {
                            ObraId = 3,
                            RepartoId = 22
                        },
                        new
                        {
                            ObraId = 3,
                            RepartoId = 23
                        },
                        new
                        {
                            ObraId = 3,
                            RepartoId = 24
                        },
                        new
                        {
                            ObraId = 4,
                            RepartoId = 25
                        },
                        new
                        {
                            ObraId = 4,
                            RepartoId = 26
                        },
                        new
                        {
                            ObraId = 4,
                            RepartoId = 27
                        },
                        new
                        {
                            ObraId = 4,
                            RepartoId = 28
                        },
                        new
                        {
                            ObraId = 4,
                            RepartoId = 29
                        },
                        new
                        {
                            ObraId = 4,
                            RepartoId = 30
                        },
                        new
                        {
                            ObraId = 4,
                            RepartoId = 31
                        },
                        new
                        {
                            ObraId = 4,
                            RepartoId = 32
                        },
                        new
                        {
                            ObraId = 5,
                            RepartoId = 33
                        },
                        new
                        {
                            ObraId = 5,
                            RepartoId = 34
                        },
                        new
                        {
                            ObraId = 5,
                            RepartoId = 35
                        },
                        new
                        {
                            ObraId = 5,
                            RepartoId = 36
                        },
                        new
                        {
                            ObraId = 5,
                            RepartoId = 37
                        },
                        new
                        {
                            ObraId = 5,
                            RepartoId = 38
                        },
                        new
                        {
                            ObraId = 5,
                            RepartoId = 39
                        },
                        new
                        {
                            ObraId = 5,
                            RepartoId = 40
                        },
                        new
                        {
                            ObraId = 6,
                            RepartoId = 41
                        },
                        new
                        {
                            ObraId = 6,
                            RepartoId = 42
                        },
                        new
                        {
                            ObraId = 6,
                            RepartoId = 43
                        },
                        new
                        {
                            ObraId = 6,
                            RepartoId = 44
                        },
                        new
                        {
                            ObraId = 6,
                            RepartoId = 45
                        },
                        new
                        {
                            ObraId = 6,
                            RepartoId = 46
                        },
                        new
                        {
                            ObraId = 6,
                            RepartoId = 47
                        },
                        new
                        {
                            ObraId = 6,
                            RepartoId = 48
                        },
                        new
                        {
                            ObraId = 7,
                            RepartoId = 49
                        },
                        new
                        {
                            ObraId = 7,
                            RepartoId = 50
                        },
                        new
                        {
                            ObraId = 7,
                            RepartoId = 51
                        },
                        new
                        {
                            ObraId = 7,
                            RepartoId = 52
                        },
                        new
                        {
                            ObraId = 7,
                            RepartoId = 53
                        },
                        new
                        {
                            ObraId = 7,
                            RepartoId = 54
                        },
                        new
                        {
                            ObraId = 7,
                            RepartoId = 55
                        },
                        new
                        {
                            ObraId = 7,
                            RepartoId = 56
                        },
                        new
                        {
                            ObraId = 8,
                            RepartoId = 57
                        },
                        new
                        {
                            ObraId = 8,
                            RepartoId = 58
                        },
                        new
                        {
                            ObraId = 8,
                            RepartoId = 59
                        },
                        new
                        {
                            ObraId = 8,
                            RepartoId = 60
                        },
                        new
                        {
                            ObraId = 8,
                            RepartoId = 61
                        },
                        new
                        {
                            ObraId = 8,
                            RepartoId = 62
                        },
                        new
                        {
                            ObraId = 8,
                            RepartoId = 63
                        },
                        new
                        {
                            ObraId = 8,
                            RepartoId = 64
                        },
                        new
                        {
                            ObraId = 9,
                            RepartoId = 65
                        },
                        new
                        {
                            ObraId = 9,
                            RepartoId = 66
                        },
                        new
                        {
                            ObraId = 9,
                            RepartoId = 67
                        },
                        new
                        {
                            ObraId = 9,
                            RepartoId = 68
                        },
                        new
                        {
                            ObraId = 9,
                            RepartoId = 69
                        },
                        new
                        {
                            ObraId = 9,
                            RepartoId = 70
                        },
                        new
                        {
                            ObraId = 9,
                            RepartoId = 71
                        },
                        new
                        {
                            ObraId = 9,
                            RepartoId = 72
                        },
                        new
                        {
                            ObraId = 10,
                            RepartoId = 73
                        },
                        new
                        {
                            ObraId = 10,
                            RepartoId = 74
                        },
                        new
                        {
                            ObraId = 10,
                            RepartoId = 75
                        },
                        new
                        {
                            ObraId = 10,
                            RepartoId = 76
                        },
                        new
                        {
                            ObraId = 10,
                            RepartoId = 77
                        },
                        new
                        {
                            ObraId = 10,
                            RepartoId = 78
                        },
                        new
                        {
                            ObraId = 10,
                            RepartoId = 79
                        },
                        new
                        {
                            ObraId = 10,
                            RepartoId = 80
                        },
                        new
                        {
                            ObraId = 11,
                            RepartoId = 81
                        },
                        new
                        {
                            ObraId = 11,
                            RepartoId = 82
                        },
                        new
                        {
                            ObraId = 11,
                            RepartoId = 83
                        },
                        new
                        {
                            ObraId = 11,
                            RepartoId = 84
                        },
                        new
                        {
                            ObraId = 11,
                            RepartoId = 85
                        },
                        new
                        {
                            ObraId = 11,
                            RepartoId = 86
                        },
                        new
                        {
                            ObraId = 11,
                            RepartoId = 87
                        },
                        new
                        {
                            ObraId = 11,
                            RepartoId = 88
                        },
                        new
                        {
                            ObraId = 12,
                            RepartoId = 89
                        },
                        new
                        {
                            ObraId = 12,
                            RepartoId = 90
                        },
                        new
                        {
                            ObraId = 12,
                            RepartoId = 91
                        },
                        new
                        {
                            ObraId = 12,
                            RepartoId = 92
                        },
                        new
                        {
                            ObraId = 12,
                            RepartoId = 93
                        },
                        new
                        {
                            ObraId = 12,
                            RepartoId = 94
                        },
                        new
                        {
                            ObraId = 12,
                            RepartoId = 95
                        },
                        new
                        {
                            ObraId = 12,
                            RepartoId = 96
                        });
                });

            modelBuilder.Entity("Tickett.Models.Reparto", b =>
                {
                    b.Property<int>("RepartoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RepartoId"), 1L, 1);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RepartoId");

                    b.ToTable("Repartos");

                    b.HasData(
                        new
                        {
                            RepartoId = 1,
                            Nombre = "Luisa Fernández",
                            Rol = "Doña Ana"
                        },
                        new
                        {
                            RepartoId = 2,
                            Nombre = "Andrés Sánchez",
                            Rol = "Don Juan"
                        },
                        new
                        {
                            RepartoId = 3,
                            Nombre = "María Gómez",
                            Rol = "Doña Inés"
                        },
                        new
                        {
                            RepartoId = 4,
                            Nombre = "Javier Rodríguez",
                            Rol = "Don Luis"
                        },
                        new
                        {
                            RepartoId = 5,
                            Nombre = "Elena Pérez",
                            Rol = "Doña Elvira"
                        },
                        new
                        {
                            RepartoId = 6,
                            Nombre = "Carlos Martínez",
                            Rol = "Molière"
                        },
                        new
                        {
                            RepartoId = 7,
                            Nombre = "Ana Ruiz",
                            Rol = "Sganarelle"
                        },
                        new
                        {
                            RepartoId = 8,
                            Nombre = "Pedro Vázquez",
                            Rol = "Don Gonzalo"
                        },
                        new
                        {
                            RepartoId = 9,
                            Nombre = "Sofía Martínez",
                            Rol = "Celestina"
                        },
                        new
                        {
                            RepartoId = 10,
                            Nombre = "Diego López",
                            Rol = "Calisto"
                        },
                        new
                        {
                            RepartoId = 11,
                            Nombre = "Lucía García",
                            Rol = "Melibea"
                        },
                        new
                        {
                            RepartoId = 12,
                            Nombre = "Javier Rodríguez",
                            Rol = "Sempronio"
                        },
                        new
                        {
                            RepartoId = 13,
                            Nombre = "Elena Pérez",
                            Rol = "Elicia"
                        },
                        new
                        {
                            RepartoId = 14,
                            Nombre = "Carlos Gómez",
                            Rol = "Tristán"
                        },
                        new
                        {
                            RepartoId = 15,
                            Nombre = "Ana Ruiz",
                            Rol = "Pármeno"
                        },
                        new
                        {
                            RepartoId = 16,
                            Nombre = "Pedro Vázquez",
                            Rol = "Alisa"
                        },
                        new
                        {
                            RepartoId = 17,
                            Nombre = "Luis García",
                            Rol = "Chris"
                        },
                        new
                        {
                            RepartoId = 18,
                            Nombre = "María López",
                            Rol = "Annie"
                        },
                        new
                        {
                            RepartoId = 19,
                            Nombre = "Andrés Martínez",
                            Rol = "Jonathan"
                        },
                        new
                        {
                            RepartoId = 20,
                            Nombre = "Elena Rodríguez",
                            Rol = "Sandra"
                        },
                        new
                        {
                            RepartoId = 21,
                            Nombre = "Carlos Ruiz",
                            Rol = "Max"
                        },
                        new
                        {
                            RepartoId = 22,
                            Nombre = "Lucía González",
                            Rol = "Dennis"
                        },
                        new
                        {
                            RepartoId = 23,
                            Nombre = "Javier Fernández",
                            Rol = "Trevor"
                        },
                        new
                        {
                            RepartoId = 24,
                            Nombre = "Ana Pérez",
                            Rol = "Robert"
                        },
                        new
                        {
                            RepartoId = 25,
                            Nombre = "Erik Larsson",
                            Rol = "Olaf, guía sami"
                        },
                        new
                        {
                            RepartoId = 26,
                            Nombre = "Ingrid Johansson",
                            Rol = "Kaisa, chamán sami"
                        },
                        new
                        {
                            RepartoId = 27,
                            Nombre = "Sven Andersson",
                            Rol = "Bjorn, explorador"
                        },
                        new
                        {
                            RepartoId = 28,
                            Nombre = "Hanna Bergman",
                            Rol = "Lena, viajera aventurera"
                        },
                        new
                        {
                            RepartoId = 29,
                            Nombre = "Frida Nilsson",
                            Rol = "Elsa, niña sami"
                        },
                        new
                        {
                            RepartoId = 30,
                            Nombre = "Oskar Magnusson",
                            Rol = "Gunnar, habitante local"
                        },
                        new
                        {
                            RepartoId = 31,
                            Nombre = "Emma Karlsson",
                            Rol = "Sofia, fotógrafa"
                        },
                        new
                        {
                            RepartoId = 32,
                            Nombre = "Viktor Lindström",
                            Rol = "Ole, cazador"
                        },
                        new
                        {
                            RepartoId = 33,
                            Nombre = "Ana García",
                            Rol = "José"
                        },
                        new
                        {
                            RepartoId = 34,
                            Nombre = "Luis Martínez",
                            Rol = "Jacob"
                        },
                        new
                        {
                            RepartoId = 35,
                            Nombre = "María Fernández",
                            Rol = "Rebeca"
                        },
                        new
                        {
                            RepartoId = 36,
                            Nombre = "Javier Rodríguez",
                            Rol = "Faraón"
                        },
                        new
                        {
                            RepartoId = 37,
                            Nombre = "Elena Pérez",
                            Rol = "Esposa de Potifar"
                        },
                        new
                        {
                            RepartoId = 38,
                            Nombre = "Carlos Sánchez",
                            Rol = "Potifar"
                        },
                        new
                        {
                            RepartoId = 39,
                            Nombre = "Lucía Martín",
                            Rol = "Mayordomo"
                        },
                        new
                        {
                            RepartoId = 40,
                            Nombre = "Andrés Gómez",
                            Rol = "Elvisar"
                        },
                        new
                        {
                            RepartoId = 41,
                            Nombre = "Javier Martínez",
                            Rol = "El Mago Pop (Antonio Díaz)"
                        },
                        new
                        {
                            RepartoId = 42,
                            Nombre = "Lucía García",
                            Rol = "Asistente del Mago"
                        },
                        new
                        {
                            RepartoId = 43,
                            Nombre = "Andrés Fernández",
                            Rol = "Participante del Público"
                        },
                        new
                        {
                            RepartoId = 44,
                            Nombre = "María López",
                            Rol = "Asistente Técnico"
                        },
                        new
                        {
                            RepartoId = 45,
                            Nombre = "Carlos Ruiz",
                            Rol = "Encargado de Escenario"
                        },
                        new
                        {
                            RepartoId = 46,
                            Nombre = "Elena Sánchez",
                            Rol = "Coordinador de Efectos Especiales"
                        },
                        new
                        {
                            RepartoId = 47,
                            Nombre = "Pedro González",
                            Rol = "Diseñador de Iluminación"
                        },
                        new
                        {
                            RepartoId = 48,
                            Nombre = "Ana Martín",
                            Rol = "Gerente de Producción"
                        },
                        new
                        {
                            RepartoId = 49,
                            Nombre = "Sofía Martínez",
                            Rol = "Lena, la ilusionista"
                        },
                        new
                        {
                            RepartoId = 50,
                            Nombre = "Diego López",
                            Rol = "David, el aprendiz de mago"
                        },
                        new
                        {
                            RepartoId = 51,
                            Nombre = "Lucía García",
                            Rol = "María, la asistente"
                        },
                        new
                        {
                            RepartoId = 52,
                            Nombre = "Javier Rodríguez",
                            Rol = "Carlos, el escéptico"
                        },
                        new
                        {
                            RepartoId = 53,
                            Nombre = "Elena Pérez",
                            Rol = "Laura, la espectadora"
                        },
                        new
                        {
                            RepartoId = 54,
                            Nombre = "Carlos Gómez",
                            Rol = "Jorge, el incrédulo"
                        },
                        new
                        {
                            RepartoId = 55,
                            Nombre = "Ana Ruiz",
                            Rol = "Paula, la admiradora"
                        },
                        new
                        {
                            RepartoId = 56,
                            Nombre = "Pedro Vázquez",
                            Rol = "Pablo, el curioso"
                        },
                        new
                        {
                            RepartoId = 57,
                            Nombre = "Leyla Khan",
                            Rol = "Scheherezade"
                        },
                        new
                        {
                            RepartoId = 58,
                            Nombre = "Amir Shah",
                            Rol = "Sultán Shahriar"
                        },
                        new
                        {
                            RepartoId = 59,
                            Nombre = "Jamil Ahmed",
                            Rol = "Aladino"
                        },
                        new
                        {
                            RepartoId = 60,
                            Nombre = "Nadia Malik",
                            Rol = "Jasmine"
                        },
                        new
                        {
                            RepartoId = 61,
                            Nombre = "Karim Hassan",
                            Rol = "Simbad"
                        },
                        new
                        {
                            RepartoId = 62,
                            Nombre = "Ayesha Khan",
                            Rol = "Scheherezade (joven)"
                        },
                        new
                        {
                            RepartoId = 63,
                            Nombre = "Rashid Ali",
                            Rol = "Ali Baba"
                        },
                        new
                        {
                            RepartoId = 64,
                            Nombre = "Yasir Mahmood",
                            Rol = "Genio"
                        },
                        new
                        {
                            RepartoId = 65,
                            Nombre = "Sofía Martínez",
                            Rol = "Nala"
                        },
                        new
                        {
                            RepartoId = 66,
                            Nombre = "Diego López",
                            Rol = "Simba"
                        },
                        new
                        {
                            RepartoId = 67,
                            Nombre = "Lucía García",
                            Rol = "Sarabi"
                        },
                        new
                        {
                            RepartoId = 68,
                            Nombre = "Javier Rodríguez",
                            Rol = "Mufasa"
                        },
                        new
                        {
                            RepartoId = 69,
                            Nombre = "Elena Pérez",
                            Rol = "Rafiki"
                        },
                        new
                        {
                            RepartoId = 70,
                            Nombre = "Carlos Gómez",
                            Rol = "Scar"
                        },
                        new
                        {
                            RepartoId = 71,
                            Nombre = "Ana Ruiz",
                            Rol = "Timón"
                        },
                        new
                        {
                            RepartoId = 72,
                            Nombre = "Pedro Vázquez",
                            Rol = "Pumbaa"
                        },
                        new
                        {
                            RepartoId = 73,
                            Nombre = "María García",
                            Rol = "Lola"
                        },
                        new
                        {
                            RepartoId = 74,
                            Nombre = "Javier Martínez",
                            Rol = "Pedro"
                        },
                        new
                        {
                            RepartoId = 75,
                            Nombre = "Lucía Rodríguez",
                            Rol = "Ana"
                        },
                        new
                        {
                            RepartoId = 76,
                            Nombre = "Andrés López",
                            Rol = "Juan"
                        },
                        new
                        {
                            RepartoId = 77,
                            Nombre = "Elena Pérez",
                            Rol = "Laura"
                        },
                        new
                        {
                            RepartoId = 78,
                            Nombre = "Carlos Gómez",
                            Rol = "Pablo"
                        },
                        new
                        {
                            RepartoId = 79,
                            Nombre = "Ana Ruiz",
                            Rol = "Carmen"
                        },
                        new
                        {
                            RepartoId = 80,
                            Nombre = "Pedro Vázquez",
                            Rol = "Luis"
                        },
                        new
                        {
                            RepartoId = 81,
                            Nombre = "Sara Pérez",
                            Rol = "Laura"
                        },
                        new
                        {
                            RepartoId = 82,
                            Nombre = "Javier García",
                            Rol = "Carlos"
                        },
                        new
                        {
                            RepartoId = 83,
                            Nombre = "Lucía Martínez",
                            Rol = "Ana"
                        },
                        new
                        {
                            RepartoId = 84,
                            Nombre = "Andrés López",
                            Rol = "Diego"
                        },
                        new
                        {
                            RepartoId = 85,
                            Nombre = "Elena Rodríguez",
                            Rol = "María"
                        },
                        new
                        {
                            RepartoId = 86,
                            Nombre = "Carlos Fernández",
                            Rol = "Javier"
                        },
                        new
                        {
                            RepartoId = 87,
                            Nombre = "María Gómez",
                            Rol = "Sofía"
                        },
                        new
                        {
                            RepartoId = 88,
                            Nombre = "Pedro Ruiz",
                            Rol = "Pablo"
                        },
                        new
                        {
                            RepartoId = 89,
                            Nombre = "Laura Martínez",
                            Rol = "Marina"
                        },
                        new
                        {
                            RepartoId = 90,
                            Nombre = "Diego López",
                            Rol = "Carlos"
                        },
                        new
                        {
                            RepartoId = 91,
                            Nombre = "Ana Fernández",
                            Rol = "Sandra"
                        },
                        new
                        {
                            RepartoId = 92,
                            Nombre = "Javier Gómez",
                            Rol = "Mario"
                        },
                        new
                        {
                            RepartoId = 93,
                            Nombre = "Sofía Rodríguez",
                            Rol = "Laura"
                        },
                        new
                        {
                            RepartoId = 94,
                            Nombre = "Andrés Pérez",
                            Rol = "Pedro"
                        },
                        new
                        {
                            RepartoId = 95,
                            Nombre = "Elena Ruiz",
                            Rol = "Lorena"
                        },
                        new
                        {
                            RepartoId = 96,
                            Nombre = "Carlos Martín",
                            Rol = "Pablo"
                        });
                });

            modelBuilder.Entity("Tickett.Models.Sesion", b =>
                {
                    b.Property<int>("SesionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SesionId"), 1L, 1);

                    b.Property<DateTime>("DiaObra")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("HoraObra")
                        .HasColumnType("time");

                    b.Property<int>("ObraId")
                        .HasColumnType("int");

                    b.HasKey("SesionId");

                    b.HasIndex("ObraId");

                    b.ToTable("Sesiones");

                    b.HasData(
                        new
                        {
                            SesionId = 1,
                            DiaObra = new DateTime(2024, 1, 13, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            HoraObra = new TimeSpan(0, 0, 0, 0, 0),
                            ObraId = 1
                        });
                });

            modelBuilder.Entity("Tickett.Models.Butaca", b =>
                {
                    b.HasOne("Tickett.Models.Obra", "Obra")
                        .WithMany()
                        .HasForeignKey("ObraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tickett.Models.Sesion", null)
                        .WithMany("ListaButacas")
                        .HasForeignKey("SesionId");

                    b.Navigation("Obra");
                });

            modelBuilder.Entity("Tickett.Models.ObraReparto", b =>
                {
                    b.HasOne("Tickett.Models.Obra", "Obra")
                        .WithMany("ListaObraReparto")
                        .HasForeignKey("ObraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tickett.Models.Reparto", "Reparto")
                        .WithMany("ListaObraReparto")
                        .HasForeignKey("RepartoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Obra");

                    b.Navigation("Reparto");
                });

            modelBuilder.Entity("Tickett.Models.Sesion", b =>
                {
                    b.HasOne("Tickett.Models.Obra", "Obra")
                        .WithMany()
                        .HasForeignKey("ObraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Obra");
                });

            modelBuilder.Entity("Tickett.Models.Obra", b =>
                {
                    b.Navigation("ListaObraReparto");
                });

            modelBuilder.Entity("Tickett.Models.Reparto", b =>
                {
                    b.Navigation("ListaObraReparto");
                });

            modelBuilder.Entity("Tickett.Models.Sesion", b =>
                {
                    b.Navigation("ListaButacas");
                });
#pragma warning restore 612, 618
        }
    }
}
